AWSTemplateFormatVersion: '2010-09-09'

Description: >
  AWS CloudFormation template to create a VPC, Internet Gateway,
  Public and Private Subnets, Route Table, and Route Table Association.

Resources:

  FirstVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: first-vpc-task
        - Key: Environment
          Value: dev
        - Key: Project
          Value: Networking

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: first-igw
        - Key: Environment
          Value: dev
        - Key: Project
          Value: Networking

  AttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref FirstVPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref FirstVPC
      Tags:
        - Key: Name
          Value: public-route-table
        - Key: Environment
          Value: dev
        - Key: Project
          Value: Networking

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachInternetGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref FirstVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: us-east-1a
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: public-subnet
        - Key: Environment
          Value: dev
        - Key: Project
          Value: Networking

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref FirstVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: us-east-1a
      Tags:
        - Key: Name
          Value: private-subnet
        - Key: Environment
          Value: dev
        - Key: Project
          Value: Networking

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet

Outputs:

  VPCId:
    Description: VPC ID
    Value: !Ref FirstVPC

  PublicSubnetId:
    Description: Public Subnet ID
    Value: !Ref PublicSubnet

  PrivateSubnetId:
    Description: Private Subnet ID
    Value: !Ref PrivateSubnet

  InternetGatewayId:
    Description: Internet Gateway ID
    Value: !Ref InternetGateway

  PublicRouteTableId:
    Description: Public Route Table ID
    Value: !Ref PublicRouteTable